version: '3'
services:
  web:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start
  nginx:
    build:
      context: .
    ports:
      - "80:80"
